MA-24190 media: ox05b1s: Move variable declarations to fix C23 build error
Fix build error caused by variable declaration immediately after
a case label, which violates pre-C23 standards:

  drivers/media/i2c/ox05b1s/ox05b1s_mipi.c:737:3: error: label
  followed by a declaration is a C23 extension
  [-Werror,-Wc23-extensions]

Move the long_exp and short_exp variable declarations to the
beginning of the ox05b1s_s_ctrl() function.

Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>