gpu: mali: update shmem_[kernel]_file_*() functions to use vma_flags_t
Cope with upstream API change:
commit 590d356aa433 ("mm: update shmem_[kernel]_file_*() functions to use vma_flags_t")

In file included from ../drivers/gpu/arm/midgard/csf/mali_kbase_csf.c:30:
../include/linux/shmem_fs.h:105:74: note: expected ‘vma_flags_t’ but argument is of type ‘long unsigned int’
  105 | struct file *shmem_file_setup(const char *name, loff_t size, vma_flags_t flags);
      |                                                              ~~~~~~~~~~~~^~~~~
../drivers/gpu/arm/midgard/csf/mali_kbase_csf.c: In function ‘kbase_csf_setup_dummy_user_reg_page’:
../include/vdso/bits.h:7:33: error: incompatible type for argument 3 of ‘shmem_file_setup’
    7 | #define BIT(nr)                 (UL(1) << (nr))
      |                                 ^~~~~~~~~~~~~~~
      |                                 |
      |                                 long unsigned int
../include/linux/mm.h:401:28: note: in expansion of macro ‘BIT’
  401 | #define INIT_VM_FLAG(name) BIT((__force int) VMA_ ## name ## _BIT)
      |                            ^~~
../include/linux/mm.h:428:25: note: in expansion of macro ‘INIT_VM_FLAG’
  428 | #define VM_NORESERVE    INIT_VM_FLAG(NORESERVE)
      |                         ^~~~~~~~~~~~

Signed-off-by: Jiyu Yang <jiyu.yang@nxp.com>