leds: tlc591xx: fix c99 compile error when change to kernel module
Error message as following:
error: mixing declarations and code is a C99 extension

Need initial the variable first.